server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opcua_device?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      min: trace

opcua:
  server:
    name: OPC-UA Default Server
    url: opc.tcp://0.0.0.0:4840
    timeoutInMillis: 5000
    scanPeriodInMillis: 1000
    disableSubscriptions: false
    subCheckPeriodInMillis: 100
    showMap: false
    security: Basic123Rsa15
  mapping:
    deviceNodePattern: Device[0-9]+
    deviceNamePattern: Name
    timeseries: {Temperature: Temperature,Humidity: Humidity,BatteryLevel: BatteryLevel}